"""
Django settings for chileavanza project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse, unquote
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar las variables desde el archivo .env
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

# ==============================================================================
# HOSTS Y CSRF DINÁMICOS DESDE EL ENTORNO (.env / Railway)
# ==============================================================================
_allowed_hosts_env = os.getenv('ALLOWED_HOSTS')
if _allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_env.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = [
        'smartbids.chileavanza.cl',
        'chileavanza.cl',
        '.chileavanza.cl',
        '.railway.app',
        '.up.railway.app',
        '127.0.0.1',
        'localhost',
        '*',
    ]

_csrf_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS')
if _csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_origins_env.split(',') if origin.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://smartbids.chileavanza.cl',
        'https://*.railway.app',
        'https://*.up.railway.app',
        'https://chileavanza.cl',
        'https://*.chileavanza.cl',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'smartbids',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'smartbids.storage_guard.StorageSafetyMiddleware',  # Guardián de almacenamiento (mejoras)
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',       # Requerido para servir estáticos en Railway
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chileavanza.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'] if (BASE_DIR / 'templates').exists() else [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'chileavanza.settings.firebase_settings',
                'smartbids.context_processors.footer_info_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'chileavanza.wsgi.application'


# Database
# Compatible con la red interna privada de Railway y fallback para desarrollo local
_db_url_env = os.getenv('DATABASE_PRIVATE_URL') or os.getenv('DATABASE_URL')

if _db_url_env:
    _url = urlparse(_db_url_env)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _url.path.lstrip('/'),
            'USER': unquote(_url.username or ''),
            'PASSWORD': unquote(_url.password or ''),
            'HOST': _url.hostname,
            'PORT': _url.port or 5432,
            'OPTIONS': {
                'options': '-c search_path=public,catalog,procurement,core,config'
            },
        },
        'dw': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DW_DB_NAME', 'smartbids_dw'),
            'USER': unquote(_url.username or ''),
            'PASSWORD': unquote(_url.password or ''),
            'HOST': _url.hostname,
            'PORT': _url.port or 5432,
            'OPTIONS': {
                'options': '-c search_path=dw,public'
            },
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'smartbids'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'options': '-c search_path=public,catalog,procurement,core,config'
            },
        },
        'dw': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DW_DB_NAME', 'smartbids_dw'),
            'USER': os.getenv('DW_DB_USER', os.getenv('DB_USER', 'postgres')),
            'PASSWORD': os.getenv('DW_DB_PASSWORD', os.getenv('DB_PASSWORD', '')),
            'HOST': os.getenv('DW_DB_HOST', os.getenv('DB_HOST', 'localhost')),
            'PORT': os.getenv('DW_DB_PORT', os.getenv('DB_PORT', '5432')),
            'OPTIONS': {
                'options': '-c search_path=dw,public'
            },
        },
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

if (BASE_DIR / 'static').exists():
    STATICFILES_DIRS = [
        BASE_DIR / 'static',
    ]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# CONFIGURACIÓN DEL SERVIDOR DE CORREOS (GMAIL API REST)
# ==============================================================================
EMAIL_BACKEND = 'smartbids.gmail_backend.GmailApiBackend'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'smartbids.qa@chileavanza.cl')
DEFAULT_FROM_EMAIL = f"SmartBids <{EMAIL_HOST_USER}>"

# ==============================================================================
# FIREBASE CONFIGURATION
# ==============================================================================
FIREBASE_CONFIG = {
    'apiKey': os.getenv('FIREBASE_API_KEY'),
    'authDomain': os.getenv('FIREBASE_AUTH_DOMAIN'),
    'projectId': os.getenv('FIREBASE_PROJECT_ID'),
    'storageBucket': os.getenv('FIREBASE_STORAGE_BUCKET'),
    'messagingSenderId': os.getenv('FIREBASE_MESSAGING_SENDER_ID'),
    'appId': os.getenv('FIREBASE_APP_ID'),
    'measurementId': os.getenv('FIREBASE_MEASUREMENT_ID'),
}

def firebase_settings(request):
    return {
        'FIREBASE_CONFIG': FIREBASE_CONFIG
    }