# Generated by Django 5.2.17 on 2026-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('tipo_alerta', models.CharField(choices=[('alerta', 'Alerta'), ('precaucion', 'Precaución'), ('exito', 'Éxito')], default='alerta', max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensajería',
                'verbose_name_plural': 'Mensajerías',
                'db_table': 'mensajeria',
            },
        ),
    ]
