# Generated by Django 6.1 on 2026-08-18 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambito',
            fields=[
                ('codigo_ambito', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_ambito', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ambito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('codigo_comuna', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoProducto',
            fields=[
                ('codigo_grupo_producto', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_grupo_producto', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'grupo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel1Producto',
            fields=[
                ('codigo_nivel1', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel1_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel2Producto',
            fields=[
                ('id_nivel2', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_nivel2', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'nivel2_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel3Producto',
            fields=[
                ('id_nivel3', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_nivel3', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'nivel3_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('codigo_organismo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('organismo', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=30, null=True)),
                ('rut', models.CharField(max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('reclamos', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'organismo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('codigo_nivel4', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigo_provincia', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('codigo_region', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('codigo_sector', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_sector', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoLicitacion',
            fields=[
                ('codigo_tipo_licitacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_licitacion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_licitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('codigo_procedimiento', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('glosa', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tipo_procedimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TramoLicitacion',
            fields=[
                ('codigo_tramo_licitacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_tramo_licitacion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tramo_licitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadCompra',
            fields=[
                ('codigo_unidad_compra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidad_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('codigo_unidad_medida', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_unidad_medida', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'unidad_medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSuscriptor',
            fields=[
                ('codigo_estado', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"config"."estado_suscriptor"',
            },
        ),
        migrations.CreateModel(
            name='RubroActividad',
            fields=[
                ('codigo_rubro', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre_rubro', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': '"catalog"."rubro_actividad"',
            },
        ),
        migrations.CreateModel(
            name='TipoPreferencia',
            fields=[
                ('codigo_tipo_preferencia', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_preferencia', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"config"."tipo_preferencia"',
            },
        ),
        migrations.CreateModel(
            name='SubrubroActividad',
            fields=[
                ('codigo_subrubro', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_subrubro', models.CharField(max_length=200)),
                ('rubro', models.ForeignKey(db_column='codigo_rubro', on_delete=django.db.models.deletion.PROTECT, to='smartbids.rubroactividad')),
            ],
            options={
                'db_table': '"catalog"."subrubro_actividad"',
            },
        ),
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('codigo_actividad', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=300)),
                ('afecto_iva', models.BooleanField()),
                ('categoria_tributaria', models.SmallIntegerField()),
                ('disponible_internet', models.BooleanField()),
                ('activo', models.BooleanField(default=True)),
                ('subrubro', models.ForeignKey(db_column='codigo_subrubro', on_delete=django.db.models.deletion.PROTECT, to='smartbids.subrubroactividad')),
            ],
            options={
                'db_table': '"catalog"."actividad_economica"',
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id_suscriptor', models.BigAutoField(primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_suscriptor', models.ForeignKey(db_column='codigo_estado', on_delete=django.db.models.deletion.PROTECT, to='smartbids.estadosuscriptor')),
            ],
            options={
                'db_table': '"core"."suscriptor"',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('inicial_empresa', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_destinatario', models.EmailField(help_text='Correo principal para recibir notificaciones de SmartBids.', max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comuna', models.ForeignKey(blank=True, db_column='codigo_comuna', null=True, on_delete=django.db.models.deletion.PROTECT, to='smartbids.comuna')),
                ('suscriptor', models.OneToOneField(db_column='id_suscriptor', on_delete=django.db.models.deletion.PROTECT, to='smartbids.suscriptor')),
            ],
            options={
                'db_table': '"core"."empresa"',
            },
        ),
        migrations.CreateModel(
            name='EmpresaActividadEconomica',
            fields=[
                ('id_empresa_actividad', models.BigAutoField(primary_key=True, serialize=False)),
                ('principal', models.BooleanField(default=False)),
                ('actividad_economica', models.ForeignKey(db_column='codigo_actividad', on_delete=django.db.models.deletion.PROTECT, to='smartbids.actividadeconomica')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='smartbids.empresa')),
            ],
            options={
                'db_table': '"core"."empresa_actividad_economica"',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'actividad_economica'), name='uq_empresa_actividad')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaCorreoCopia',
            fields=[
                ('id_correo_copia', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='correos_copia', to='smartbids.empresa')),
            ],
            options={
                'db_table': '"core"."empresa_correo_copia"',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'correo'), name='uq_empresa_correo_copia')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaProducto',
            fields=[
                ('id_empresa_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='smartbids.empresa')),
                ('producto', models.ForeignKey(db_column='codigo_producto', on_delete=django.db.models.deletion.PROTECT, to='smartbids.producto')),
                ('tipo_preferencia', models.ForeignKey(db_column='codigo_tipo_preferencia', on_delete=django.db.models.deletion.PROTECT, to='smartbids.tipopreferencia')),
            ],
            options={
                'db_table': '"core"."empresa_producto"',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'producto'), name='uq_empresa_producto')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaPalabraClave',
            fields=[
                ('id_empresa_palabra', models.BigAutoField(primary_key=True, serialize=False)),
                ('palabra', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='smartbids.empresa')),
                ('tipo_preferencia', models.ForeignKey(db_column='codigo_tipo_preferencia', on_delete=django.db.models.deletion.PROTECT, to='smartbids.tipopreferencia')),
            ],
            options={
                'db_table': '"core"."empresa_palabra_clave"',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'palabra'), name='uq_empresa_palabra')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaOrganismo',
            fields=[
                ('id_empresa_organismo', models.BigAutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='smartbids.empresa')),
                ('organismo', models.ForeignKey(db_column='codigo_organismo', on_delete=django.db.models.deletion.PROTECT, to='smartbids.organismo')),
                ('tipo_preferencia', models.ForeignKey(db_column='codigo_tipo_preferencia', on_delete=django.db.models.deletion.PROTECT, to='smartbids.tipopreferencia')),
            ],
            options={
                'db_table': '"core"."empresa_organismo"',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'organismo'), name='uq_empresa_organismo')],
            },
        ),
    ]
